name: Mdc Workflow

on:
  push:
    branches:
      - main # Ou 'master', dependendo do nome da sua branch principal
      - feature/intro-devops # branch criada para codar os testes antes de levar a branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2 # Action para clonar o repositório

      - name: Mostrar Mensagem
        run: echo "Olá, testando GitHub Actions!" # Comando a ser executado